version: '3.1'

name: geek

services:
  plex:
    container_name: plex-server
    hostname: jediflix
    # image: plexinc/pms-docker
    image: lscr.io/linuxserver/plex:latest
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Sao_Paulo
      - PLEX_CLAIM=claim-xWYAYghHF_fzPJRhBTgt
      - ADVERTISE_IP=http://jediflix.geek.net:32400/
    volumes:
      - ./plex/transcode:/transcode
      - ./plex/database:/config
      - ./plex/media:/data
    networks:
      - geek.net

    deploy:
      resources:
        limits:
          cpus: '3.00'
          memory: 512M
        reservations:
          cpus: '1.00'
          memory: 128M

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: always
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8182
    hostname: qbittorrent
    volumes:
      - ./qbittorrent/config:/config
      - ./plex/media:/downloads
    ports:
      - 8182:8182
      - 6881:6881/tcp
      - 6881:6881/udp
    depends_on:
      - plex
    networks:
      - geek.net

    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 64M

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    hostname: tautulli
    volumes:
      - ./tautulli/config:/config
    ports:
      - 8181:8181
    depends_on:
      - plex
    networks:
      - geek.net

    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

networks:
  geek.net:
    name: geek.net  
    driver: bridge