version: '3'
name: my-plex-server
services:
  plex:
    container_name: plex-media-server
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Sao_Paulo
      - PLEX_CLAIM=YOUR_SERVER_CLAIM_KEY
      - ADVERTISE_IP=http://LOCAL_IP:32400/
    hostname: JEDIFLIX 3.0
    volumes:
      - ./plex/transcode:/transcode
      - ./plex/database:/config
      - ./plex/media:/data
    networks:
      - skywalker-network
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./plex/media:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    depends_on:
      - plex
    networks:
      - skywalker-network
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    depends_on:
      - plex
    networks:
      - skywalker-network
networks:
  skywalker-network:
    name: skywalker-network
    driver: bridge
