version: '3'
name: tatooine
services:
  streamer:
    container_name: streamer
    image: plexinc/pms-docker
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Sao_Paulo
      - PLEX_CLAIM=claim-Rx1CX3_TsfoJ1A3SpsD1
      - ADVERTISE_IP=http://172.16.1.10:32400/
    hostname: JEDIFLIX
    volumes:
      - ./plex/transcode:/transcode
      - ./plex/database:/config
      - ./plex/media:/data
    networks:
      - skywalker-network
  downloads:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: always
    container_name: downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8182
    volumes:
      - ./qbittorrent/config:/config
      - ./plex/media:/downloads
    ports:
      - 8182:8182
      - 6881:6881
      - 6881:6881/udp
    depends_on:
      - streamer
    networks:
      - skywalker-network
  monitoring:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: monitoring
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./tautulli/config:/config
    ports:
      - 8181:8181
    depends_on:
      - streamer
    networks:
      - skywalker-network
networks:
  skywalker-network:
    name: skywalker-network
    driver: bridge
